config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    confirmations: "public/confirmations",
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about', to: 'homes#about', as: "about"
    get 'homes/privacy', to: 'homes#privacy', as: 'privacy'
    get 'homes/terms-of-use', to: 'homes#use', as: 'terms_of_use'
    get 'homes/organization', to: 'homes#organization', as: 'organization'
    resources :users, only: [:show, :update]
    get '/mypage' => 'users#mypage', as: "mypage"
    get '/mypage/setmoney' => 'users#set_money', as: "set_money"
    post '/mypage' => 'users#create_money', as: "create_money"
    patch '/mypage/setmoney' => 'users#set_save_money', as: "set_save_money"
    get '/mypage/edit'=>'users#edit', as: "edit_user"
    get 'mypage/unsubscribed' => 'users#unsubscribed', as: 'confirm_unsubscribed'
    patch '/mypage' => 'users#withdrawal', as: 'withdrawal'
    resources :spends, only: [:new, :index, :create]
    resources :spend_genres, except: [:show]
    resources :incomes, only: [:new, :index, :create]
  end
 
  namespace :admin do
    root to: 'homes#top'
    get 'dashboards', to: 'dashboards#index', as: "dashboards"
  end
  
end

app/views/layouts/_admin.html.erb
<header class="bg-admin-header">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <h1 class="p-1 text-light">管理者</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <% if admin_signed_in? %>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "トップ", admin_dashboards_path, class: 'nav-link text-light' %>
                        </li>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "収入の入力", new_income_path, class: 'nav-link text-light' %>
                        </li>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "支出の入力", new_spend_path, class: 'nav-link text-light' %>
                        </li>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "ユーザー情報", edit_user_path, class: 'nav-link text-light' %>
                        </li>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                        </li>
                    <% else %>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "トップ", admin_root_path, class: 'nav-link text-light' %>
                        </li>
                        <li class="nav-item header_btn me-4">
                            <%= link_to "ログイン", new_admin_session_path, class: 'nav-link text-light' %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_admin_footer.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-4">
      <p class="text-light">管理者用ページ</p>
      <%= image_tag '', :size =>'300x75' %>
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-3">
      <h6 class="mt-2 mb-3 text-light">Help</h6>
      <ul class="p-0 list-unstyled">
        <li><%=link_to "アクセス権限について", admin_root_path, class: "text-light"%></li>
        <li class="pt-2"><%=link_to "管理者画面に関する使い方", admin_root_path, class: "text-light"%></li>
      </ul>
    </div>

    <div class="col-md-4">
      <h6 class="mt-2 mb-3 text-light">Information</h6>
      <ul class="p-0 list-unstyled">
        <li>
          <a href="" title="About" class="text-light">注意事項</a>
        </li>
        <li class="pt-2">
          <a href="<%=admin_root_path%>" title="Terms-of-Use" class="text-light">ユーザーからの問い合わせ一覧</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="mt-3 text-center"><p><i class="fa-regular fa-copyright fa-lg" style="color: #ffffff;"></i><span class="ps-2 text-light">CHOKIN.INC</span></p><div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <p class="mb-1">貯金で余裕のあるくらしを</p>
          <%= image_tag 'rec_logo.jpg', :size =>'240x60' %>
        <p class="mt-1">© Peculiss</p>
      </div>
      <div class="col-md-2 mt-md-0">
      </div>
      <div class="col-md-3 mt-md-0 mt-3"> 
        <h6 class="mb-3">Support</h6>
        <ul class="p-0">
          <li><%=link_to "About", about_path, class: "text-light"%></li>
          <li class="pt-2"><%=link_to "使い方", root_path, class: "text-light"%></li>
          <li><a href="" title="contact" class="text-dark">問い合わせ(ブログへ遷移します)</a></li>
        </ul>
      </div>
      <div class="col-md-3 mt-md-0 mt-3">
        <h6 class="mb-3">Information</h6>
        <ul class="p-0">
          <!-- <li>
            <a href="<%=organization_path%>" title="About" class="text-light">組織について</a>
          </li> -->
          <li class="pt-0">
            <a href="<%=terms_of_use_path%>" title="Terms-of-Use" class="text-light">利用規約</a>
          </li>
          <li class="pt-2">
            <a href="<%=privacy_path%>" title="informations" class="text-light">プライバシーポリシー</a>
          </li>
          <% if user_signed_in? %>
            <li class="pt-2">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？" }, class: 'text-light'%>
            </li>
          <% end %>
          <li class="pt-2">
            <%=link_to "退会はこちらから", confirm_unsubscribed_path, class: "text-light"%>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_public.html.erb
<header class="bg-header">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <!--ブランドロゴ長方形-->
            <% if user_signed_in? %>
                <%=link_to mypage_path, class: "navbar-brand" do%>
                    <%= image_tag 'rec_logo.jpg', :size =>'200x50' %>
                <% end %>
            <%else%>
                <%=link_to root_path, class: "navbar-brand" do%>
                    <%= image_tag 'rec_logo.jpg', :size =>'200x50' %>
                <% end %>
            <%end%>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="justify-content-end collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                <%if !user_signed_in?%>
                    <li class="nav-item">
                        <%= link_to "トップ", root_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Hesokuriとは", about_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "新規登録", new_user_registration_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "ログイン", new_user_session_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                <%else%>
                    <li class="nav-item">
                        <%= link_to "マイページ", mypage_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "収入の入力", new_income_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "支出の入力", new_spend_path, class: 'text-black nav-link nav-link-space' %>
                    </li>
                <%end%>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Peculiss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0ea4f70a08.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-secondary">
    <%= yield %>
    <%=render 'layouts/footer'%>
  </body>

  <%if admin_signed_in? && !user_signed_in?%>
    <script>
      $(function(){
        $("footer").html('<%=j(render 'layouts/admin_footer')%>')
      });
    </script>
  <%end%>
</html>